import json
d = json.load(open('mapdata.json'))
o = []
w = o.append

w("# MAP.md — Mapa del monolito AlefMaster")
w("")
w("> Índice de `index.html` (18.368 líneas / 1,2 MB). **Generado automáticamente desde los 263 anchors del archivo.**")
w("> Regenerar tras cambios grandes con `genmap.py`.")
w("")
w("---")
w("")
w("## ⚠️ REGLA DE LECTURA (leer esto primero)")
w("")
w("**Nunca leer `index.html` entero.** Son ~300k tokens: consume la ventana completa en una sola lectura.")
w("")
w("Procedimiento obligatorio antes de tocar código:")
w("")
w("1. Buscar la sección en el índice de abajo → obtener rango `L_inicio–L_fin`")
w("2. Leer **solo** ese rango (`view` con `view_range`, o `sed -n 'X,Yp'`)")
w("3. Si no aparece en el índice: `grep -n \"nombreFuncion\" index.html` y leer ±40 líneas")
w("")
w("### 🚫 Líneas prohibidas (blobs de datos en una sola línea)")
w("")
w("Estas 3 líneas concentran **306 KB** — el 26% del archivo. Leerlas revienta el contexto:")
w("")
w("| Línea | Constante | Tamaño |")
w("|---|---|---|")
for ln, sz, n in d['big']:
    w(f"| **{ln}** | `{n}` | {sz//1024} KB |")
w("")
w("Para inspeccionarlas usar consultas puntuales, nunca lectura directa:")
w("")
w("```bash")
w("# ver solo las claves de ALL_DATA")
w("sed -n '2041p' index.html | grep -o '\"[A-Z0-9+]*\":{\"type\"' ")
w("# ver una parashá puntual de AUDIO_ALIYOT_MAP")
w("sed -n '2048p' index.html | python3 -c \"import sys,re,json; ...\"")
w("```")
w("")
w("---")
w("")
w("## Zonas macro")
w("")
w("| Líneas | Contenido | Notas |")
w("|---|---|---|")
w("| 1–27 | `<head>`, meta, manifest | |")
w("| 28–159 | `<style id=\"tw-minimal\">` | utilidades tipo Tailwind |")
w("| 160–169 | CDNs (confetti, supabase-js) | |")
w("| 170–765 | `<style>` principal | ~600 líneas de CSS |")
w("| 774–1983 | `<body>` — HTML de todas las views | ver índice de views |")
w("| **1984–18361** | `<script>` — **todo el JS** | ver índice de secciones |")
w("| 18365 | `<script src=\"./js/teacher.js\">` | módulo aparte (1.287 líneas) |")
w("")
w("**Ancla de extracción JS** (para scripts de patch en Python):")
w("")
w("```python")
w("m = re.search(r'<script>\\n// ── Error handling', content)   # línea 1984")
w("start = content.index('\\n', m.start()) + 1")
w("end   = content.find('</script>', start)   # find, NUNCA rindex")
w("```")
w("")
w("---")
w("")
w("## Views HTML")
w("")
w("| Línea | ID |")
w("|---|---|")
for ln, v in d['views']:
    w(f"| {ln} | `{v}` |")
w("")
w("---")
w("")
w("## Índice de secciones JS")
w("")
w(f"153 secciones top-level. Formato: `rango` · nombre · (nº de funciones).")
w("")
w("| Rango | Sección | Fns |")
w("|---|---|---|")
for s in d['sections']:
    nf = len(s['funcs'])
    w(f"| `{s['line']}–{s['end']}` | **{s['name']}** | {nf if nf else ''} |")
w("")
w("---")
w("")
w("## Detalle por sección (funciones y sub-bloques)")
w("")
for s in d['sections']:
    if not s['funcs'] and not s['subs']:
        continue
    w(f"### `{s['line']}–{s['end']}` {s['name']}")
    if s['subs']:
        w("")
        w("Sub-bloques: " + " · ".join(f"`{ln}` {name}" for ln, _, name in s['subs']))
    if s['funcs']:
        w("")
        w("Funciones: " + ", ".join(f"`{name}`({ln})" for ln, name in s['funcs']))
    w("")
w("---")
w("")
w("## Constantes / feature flags top-level")
w("")
w("| Línea | Constante | Valor (inicio) |")
w("|---|---|---|")
for ln, name, val in d['consts']:
    val = val.replace('|', '\\|')
    if len(val) > 50: val = val[:50] + '…'
    w(f"| {ln} | `{name}` | `{val}` |")
w("")
w("---")
w("")
w("## Cómo regenerar")
w("")
w("```bash")
w("python3 genmap.py     # produce mapdata.json")
w("python3 render.py     # produce MAP.md")
w("```")
w("")
w("Los anchors del código son la fuente de verdad. Al agregar una sección nueva, usar el mismo formato:")
w("")
w("```js")
w("// ── NOMBRE DE LA SECCION ──────────────────────────────")
w("```")

open('MAP.md','w').write('\n'.join(o))
import os
print('OK', os.path.getsize('MAP.md'), 'bytes')
